//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShipOnline.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdminLabel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminLabel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShipOnline.Resources.AdminLabel", typeof(AdminLabel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm xã/phường.
        /// </summary>
        public static string btnAddTown {
            get {
                return ResourceManager.GetString("btnAddTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trở về màn hình List.
        /// </summary>
        public static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy bỏ .
        /// </summary>
        public static string btnCancelOrder {
            get {
                return ResourceManager.GetString("btnCancelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi thông tin.
        /// </summary>
        public static string btnChangeInfo {
            get {
                return ResourceManager.GetString("btnChangeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        public static string btnChangePassword {
            get {
                return ResourceManager.GetString("btnChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa trường.
        /// </summary>
        public static string btnClear {
            get {
                return ResourceManager.GetString("btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận vận chuyển.
        /// </summary>
        public static string btnConfirmOrder {
            get {
                return ResourceManager.GetString("btnConfirmOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng kí.
        /// </summary>
        public static string btnRegister {
            get {
                return ResourceManager.GetString("btnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn ngày giờ nhận.
        /// </summary>
        public static string btnSelectTime {
            get {
                return ResourceManager.GetString("btnSelectTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        public static string btnUpdate {
            get {
                return ResourceManager.GetString("btnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thành phố.
        /// </summary>
        public static string CityCode {
            get {
                return ResourceManager.GetString("CityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị.
        /// </summary>
        public static string CityDispaly {
            get {
                return ResourceManager.GetString("CityDispaly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách tỉnh, thành phố.
        /// </summary>
        public static string CityListTitle {
            get {
                return ResourceManager.GetString("CityListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên thành phố.
        /// </summary>
        public static string CityName {
            get {
                return ResourceManager.GetString("CityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng kí tỉnh, thành phố.
        /// </summary>
        public static string CityRegisterTitle {
            get {
                return ResourceManager.GetString("CityRegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa tỉnh, thành phố.
        /// </summary>
        public static string CityUpdateTitle {
            get {
                return ResourceManager.GetString("CityUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bưu điện.
        /// </summary>
        public static string CityZipCode {
            get {
                return ResourceManager.GetString("CityZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xóa.
        /// </summary>
        public static string DeleteFlg {
            get {
                return ResourceManager.GetString("DeleteFlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã quận, huyện.
        /// </summary>
        public static string DistricCode {
            get {
                return ResourceManager.GetString("DistricCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên quận, huyện.
        /// </summary>
        public static string DistricName {
            get {
                return ResourceManager.GetString("DistricName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách quận, huyện.
        /// </summary>
        public static string DistrictListTitle {
            get {
                return ResourceManager.GetString("DistrictListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng kí quận, huyện.
        /// </summary>
        public static string DistrictRegisterTitle {
            get {
                return ResourceManager.GetString("DistrictRegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa quận, huyện.
        /// </summary>
        public static string DistricUpdateTitle {
            get {
                return ResourceManager.GetString("DistricUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nhóm khu vực.
        /// </summary>
        public static string GroupAreaListTitle {
            get {
                return ResourceManager.GetString("GroupAreaListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng kí nhóm khu vực.
        /// </summary>
        public static string GroupAreaRegisterTitle {
            get {
                return ResourceManager.GetString("GroupAreaRegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa nhóm khu vực.
        /// </summary>
        public static string GroupAreaUpdateTitle {
            get {
                return ResourceManager.GetString("GroupAreaUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string lblAddress {
            get {
                return ResourceManager.GetString("lblAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối tượng.
        /// </summary>
        public static string lblArea {
            get {
                return ResourceManager.GetString("lblArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cho đối tượng.
        /// </summary>
        public static string lblAreaForUser {
            get {
                return ResourceManager.GetString("lblAreaForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền.
        /// </summary>
        public static string lblAuthority {
            get {
                return ResourceManager.GetString("lblAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày khởi tạo.
        /// </summary>
        public static string lblCreateDateOrder {
            get {
                return ResourceManager.GetString("lblCreateDateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhóm khu vực.
        /// </summary>
        public static string lblGroupName {
            get {
                return ResourceManager.GetString("lblGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày đăng kí.
        /// </summary>
        public static string lblInsertDate {
            get {
                return ResourceManager.GetString("lblInsertDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội thành.
        /// </summary>
        public static string lblInside {
            get {
                return ResourceManager.GetString("lblInside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khóa.
        /// </summary>
        public static string lblLock {
            get {
                return ResourceManager.GetString("lblLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đơn hàng.
        /// </summary>
        public static string lblOrderShipCode {
            get {
                return ResourceManager.GetString("lblOrderShipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số sắp xếp.
        /// </summary>
        public static string lblOrderSort {
            get {
                return ResourceManager.GetString("lblOrderSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string lblPhone {
            get {
                return ResourceManager.GetString("lblPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiền thu hộ.
        /// </summary>
        public static string lblProductMoney {
            get {
                return ResourceManager.GetString("lblProductMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên hàng hóa.
        /// </summary>
        public static string lblProductName {
            get {
                return ResourceManager.GetString("lblProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ người nhận.
        /// </summary>
        public static string lblReceiveAddress {
            get {
                return ResourceManager.GetString("lblReceiveAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian nhận.
        /// </summary>
        public static string lblReceiveDate {
            get {
                return ResourceManager.GetString("lblReceiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người nhận.
        /// </summary>
        public static string lblReceiveName {
            get {
                return ResourceManager.GetString("lblReceiveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cước phí.
        /// </summary>
        public static string lblShipMoney {
            get {
                return ResourceManager.GetString("lblShipMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên shop/công ty.
        /// </summary>
        public static string lblShopName {
            get {
                return ResourceManager.GetString("lblShopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày đăng kí.
        /// </summary>
        public static string lblStartDate {
            get {
                return ResourceManager.GetString("lblStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày cập nhật.
        /// </summary>
        public static string lblUpdateDate {
            get {
                return ResourceManager.GetString("lblUpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài khoản.
        /// </summary>
        public static string lblUserAccount {
            get {
                return ResourceManager.GetString("lblUserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên.
        /// </summary>
        public static string lblUserName {
            get {
                return ResourceManager.GetString("lblUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng đăng nhập để tiếp tục!.
        /// </summary>
        public static string MessessLogin {
            get {
                return ResourceManager.GetString("MessessLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lí đơn hàng.
        /// </summary>
        public static string OrderShipListTitle {
            get {
                return ResourceManager.GetString("OrderShipListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng kí đơn hàng.
        /// </summary>
        public static string OrderShipRegisterTitle {
            get {
                return ResourceManager.GetString("OrderShipRegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã xã, phường.
        /// </summary>
        public static string TownCode {
            get {
                return ResourceManager.GetString("TownCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách xã, phường.
        /// </summary>
        public static string TownListTitle {
            get {
                return ResourceManager.GetString("TownListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên xã, phường.
        /// </summary>
        public static string TownName {
            get {
                return ResourceManager.GetString("TownName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng kí xã, phường.
        /// </summary>
        public static string TownRegisterTitle {
            get {
                return ResourceManager.GetString("TownRegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa xã, phường.
        /// </summary>
        public static string TownUpdateTitle {
            get {
                return ResourceManager.GetString("TownUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách người dùng.
        /// </summary>
        public static string UserListTitle {
            get {
                return ResourceManager.GetString("UserListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng kí người dùng.
        /// </summary>
        public static string UserRegisterTitle {
            get {
                return ResourceManager.GetString("UserRegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa người dùng.
        /// </summary>
        public static string UserUpdateTitle {
            get {
                return ResourceManager.GetString("UserUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin tài khoản.
        /// </summary>
        public static string UserViewTittle {
            get {
                return ResourceManager.GetString("UserViewTittle", resourceCulture);
            }
        }
    }
}
