//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShipOnline.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShipOnline.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tối đa {1} kí tự!.
        /// </summary>
        public static string CheckMaxLength {
            get {
                return ResourceManager.GetString("CheckMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tối thiểu {1} kí tự!.
        /// </summary>
        public static string CheckMinLength {
            get {
                return ResourceManager.GetString("CheckMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên thành phố tối đa 50 kí tự!.
        /// </summary>
        public static string CityNameLength {
            get {
                return ResourceManager.GetString("CityNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài mã bưu điện phải là 6 chữ số!.
        /// </summary>
        public static string CityZipCdLength {
            get {
                return ResourceManager.GetString("CityZipCdLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn chuyển sang màn hình List?.
        /// </summary>
        public static string ConfirmBack {
            get {
                return ResourceManager.GetString("ConfirmBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn xóa đã nhâp?.
        /// </summary>
        public static string ConfirmClear {
            get {
                return ResourceManager.GetString("ConfirmClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn xóa {0} ?.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa không thành công!.
        /// </summary>
        public static string ConfirmDeleteError {
            get {
                return ResourceManager.GetString("ConfirmDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn xóa dòng .
        /// </summary>
        public static string ConfirmDeleteRow {
            get {
                return ResourceManager.GetString("ConfirmDeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn {0}?.
        /// </summary>
        public static string ConfirmSubmitData {
            get {
                return ResourceManager.GetString("ConfirmSubmitData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xóa bản ghi!.
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tối đa 50 kí tự!.
        /// </summary>
        public static string DistrictNameLength {
            get {
                return ResourceManager.GetString("DistrictNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không đúng định dạng!.
        /// </summary>
        public static string IncorrectFormat {
            get {
                return ResourceManager.GetString("IncorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email đã sử dụng! Vui lòng đăng nhập!.
        /// </summary>
        public static string msgConfirmExistAccount {
            get {
                return ResourceManager.GetString("msgConfirmExistAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thành phố bị trùng!.
        /// </summary>
        public static string msgConfirmExistCd {
            get {
                return ResourceManager.GetString("msgConfirmExistCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã quận huyện bị trùng!.
        /// </summary>
        public static string msgConfirmExistDistrictCd {
            get {
                return ResourceManager.GetString("msgConfirmExistDistrictCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã xã, phường bị trùng!.
        /// </summary>
        public static string msgConfirmExistTownCd {
            get {
                return ResourceManager.GetString("msgConfirmExistTownCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email chưa được đăng ký! Vui lòng đăng ký!.
        /// </summary>
        public static string msgEmailNotExist {
            get {
                return ResourceManager.GetString("msgEmailNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn ít nhất 1 khu vực!.
        /// </summary>
        public static string msgHaveMoreAddress {
            get {
                return ResourceManager.GetString("msgHaveMoreAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu đã hết hạn. Vui lòng đổi mật khẩu!.
        /// </summary>
        public static string PasswordOnExpired {
            get {
                return ResourceManager.GetString("PasswordOnExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to đăng kí.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng kí thất bại!.
        /// </summary>
        public static string RegisterFailed {
            get {
                return ResourceManager.GetString("RegisterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng kí thành công!.
        /// </summary>
        public static string RegisterSuccess {
            get {
                return ResourceManager.GetString("RegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã đăng kí thành công! Vui lòng kiểm tra email để xác nhận!.
        /// </summary>
        public static string RegisterWaitEmail {
            get {
                return ResourceManager.GetString("RegisterWaitEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chỉnh sửa.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công!.
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
    }
}
